include(":app")
include(":domain")
include(":network")
include(":common")
include(":core:datasource")
include(":features:referral:data")
include(":features:referral:domain")
include(":features:referral:presentation")