// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dex.proto

package com.tangem.blockchain.blockchains.binance.proto;

public interface StdTxOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transaction.StdTx)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *    uint64 SIZE-OF-ENCODED // varint encoded length of the structure after encoding
   *    0xF0625DEE   // hardcoded, object type prefix in 4 bytes
   * </pre>
   *
   * <code>repeated bytes msgs = 1;</code>
   */
  java.util.List<com.google.protobuf.ByteString> getMsgsList();
  /**
   * <pre>
   *    uint64 SIZE-OF-ENCODED // varint encoded length of the structure after encoding
   *    0xF0625DEE   // hardcoded, object type prefix in 4 bytes
   * </pre>
   *
   * <code>repeated bytes msgs = 1;</code>
   */
  int getMsgsCount();
  /**
   * <pre>
   *    uint64 SIZE-OF-ENCODED // varint encoded length of the structure after encoding
   *    0xF0625DEE   // hardcoded, object type prefix in 4 bytes
   * </pre>
   *
   * <code>repeated bytes msgs = 1;</code>
   */
  com.google.protobuf.ByteString getMsgs(int index);

  /**
   * <pre>
   * array of size 1, containing the standard signature structure of the transaction sender
   * </pre>
   *
   * <code>repeated bytes signatures = 2;</code>
   */
  java.util.List<com.google.protobuf.ByteString> getSignaturesList();
  /**
   * <pre>
   * array of size 1, containing the standard signature structure of the transaction sender
   * </pre>
   *
   * <code>repeated bytes signatures = 2;</code>
   */
  int getSignaturesCount();
  /**
   * <pre>
   * array of size 1, containing the standard signature structure of the transaction sender
   * </pre>
   *
   * <code>repeated bytes signatures = 2;</code>
   */
  com.google.protobuf.ByteString getSignatures(int index);

  /**
   * <pre>
   * a short sentence of remark for the transaction. Please only `Transfer` transaction allows 'memo' input, and other transactions with non-empty `Memo` would be rejected.
   * </pre>
   *
   * <code>string memo = 3;</code>
   */
  String getMemo();
  /**
   * <pre>
   * a short sentence of remark for the transaction. Please only `Transfer` transaction allows 'memo' input, and other transactions with non-empty `Memo` would be rejected.
   * </pre>
   *
   * <code>string memo = 3;</code>
   */
  com.google.protobuf.ByteString
      getMemoBytes();

  /**
   * <pre>
   * an identifier for tools triggerring this transaction, set to zero if unwilling to disclose.
   * </pre>
   *
   * <code>int64 source = 4;</code>
   */
  long getSource();

  /**
   * <pre>
   *byte array, reserved for future use
   * </pre>
   *
   * <code>bytes data = 5;</code>
   */
  com.google.protobuf.ByteString getData();
}
