// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dex.proto

package com.tangem.blockchain.blockchains.binance.proto;

public interface TokenFreezeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transaction.TokenFreeze)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *    0xE774B32D   // hardcoded, object type prefix in 4 bytes
   * </pre>
   *
   * <code>bytes from = 1;</code>
   */
  com.google.protobuf.ByteString getFrom();

  /**
   * <pre>
   * token symbol, in full name with "-" suffix
   * </pre>
   *
   * <code>string symbol = 2;</code>
   */
  String getSymbol();
  /**
   * <pre>
   * token symbol, in full name with "-" suffix
   * </pre>
   *
   * <code>string symbol = 2;</code>
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <pre>
   * amount of token to freeze
   * </pre>
   *
   * <code>int64 amount = 3;</code>
   */
  long getAmount();
}
