// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dex.proto

package com.tangem.blockchain.binance.proto;

public interface CancelOrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transaction.CancelOrder)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *    0x166E681B   // hardcoded, object type prefix in 4 bytes
   * </pre>
   *
   * <code>bytes sender = 1;</code>
   */
  com.google.protobuf.ByteString getSender();

  /**
   * <pre>
   * symbol for trading pair in full name of the tokens
   * </pre>
   *
   * <code>string symbol = 2;</code>
   */
  String getSymbol();
  /**
   * <pre>
   * symbol for trading pair in full name of the tokens
   * </pre>
   *
   * <code>string symbol = 2;</code>
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <pre>
   * order id of the one to cancel
   * </pre>
   *
   * <code>string refid = 3;</code>
   */
  String getRefid();
  /**
   * <pre>
   * order id of the one to cancel
   * </pre>
   *
   * <code>string refid = 3;</code>
   */
  com.google.protobuf.ByteString
      getRefidBytes();
}
