// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dex.proto

package com.tangem.blockchain.binance.proto;

public interface SendOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transaction.Send)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .transaction.Send.Input inputs = 1;</code>
   */
  java.util.List<com.tangem.blockchain.binance.proto.Send.Input>
      getInputsList();
  /**
   * <code>repeated .transaction.Send.Input inputs = 1;</code>
   */
  com.tangem.blockchain.binance.proto.Send.Input getInputs(int index);
  /**
   * <code>repeated .transaction.Send.Input inputs = 1;</code>
   */
  int getInputsCount();
  /**
   * <code>repeated .transaction.Send.Input inputs = 1;</code>
   */
  java.util.List<? extends com.tangem.blockchain.binance.proto.Send.InputOrBuilder>
      getInputsOrBuilderList();
  /**
   * <code>repeated .transaction.Send.Input inputs = 1;</code>
   */
  com.tangem.blockchain.binance.proto.Send.InputOrBuilder getInputsOrBuilder(
          int index);

  /**
   * <code>repeated .transaction.Send.Output outputs = 2;</code>
   */
  java.util.List<com.tangem.blockchain.binance.proto.Send.Output>
      getOutputsList();
  /**
   * <code>repeated .transaction.Send.Output outputs = 2;</code>
   */
  com.tangem.blockchain.binance.proto.Send.Output getOutputs(int index);
  /**
   * <code>repeated .transaction.Send.Output outputs = 2;</code>
   */
  int getOutputsCount();
  /**
   * <code>repeated .transaction.Send.Output outputs = 2;</code>
   */
  java.util.List<? extends com.tangem.blockchain.binance.proto.Send.OutputOrBuilder>
      getOutputsOrBuilderList();
  /**
   * <code>repeated .transaction.Send.Output outputs = 2;</code>
   */
  com.tangem.blockchain.binance.proto.Send.OutputOrBuilder getOutputsOrBuilder(
          int index);
}
