# Dockerfile.codeql

FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
ENV ANDROID_HOME=/opt/android-sdk
ENV PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/34.0.0
ENV CODEQL_HOME=/opt/codeql
ENV PATH=$PATH:$CODEQL_HOME
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

RUN apt-get update && apt-get install -y \
    openjdk-17-jdk-headless \
    curl unzip git wget build-essential \
    python3 python3-pip ruby ruby-dev jq locales nodejs npm \
    && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && locale-gen && apt-get clean

# CodeQL CLI
RUN CODEQL_VERSION=2.16.5 && \
    curl -L -o /tmp/codeql.zip https://github.com/github/codeql-cli-binaries/releases/download/v${CODEQL_VERSION}/codeql-linux64.zip && \
    unzip /tmp/codeql.zip -d /opt && \
    mv /opt/codeql /opt/codeql-${CODEQL_VERSION} && \
    ln -s /opt/codeql-${CODEQL_VERSION} $CODEQL_HOME && \
    ln -s $CODEQL_HOME/codeql /usr/local/bin/codeql && \
    rm /tmp/codeql.zip

WORKDIR /workspace
CMD ["bash"]
