package com.tangem.core.ui.test

object AddCustomTokenScreenTestTags {
    const val CONTRACT_ADDRESS_FIELD = "ADD_CUSTOM_TOKEN_CONTRACT_ADDRESS_FIELD"
    const val DERIVATION_SELECTOR_FIELD = "ADD_CUSTOM_TOKEN_DERIVATION_SELECTOR_FIELD"
    const val CUSTOM_DERIVATION_BUTTON = "ADD_CUSTOM_TOKEN_CUSTOM_DERIVATION_BUTTON"
    const val WARNING_NOTIFICATION = "ADD_CUSTOM_TOKEN_WARNING_NOTIFICATION"
    const val SELECTOR_LIST = "ADD_CUSTOM_TOKEN_SELECTOR_LIST"

    fun networkRow(networkName: String): String = "ADD_CUSTOM_TOKEN_NETWORK_ROW_${networkName.lowercase()}"
}