package com.tangem.core.ui.test

object AppCurrencySelectorScreenTestTags {
    const val LAZY_LIST = "APP_CURRENCY_SELECTOR_SCREEN_LAZY_LIST"
    const val CURRENCY_ITEM = "APP_CURRENCY_SELECTOR_SCREEN_CURRENCY_ITEM"
    const val SEARCH_FIELD = "APP_CURRENCY_SELECTOR_SCREEN_SEARCH_FIELD"
    const val TOP_BAR_ACTION_BUTTON = "APP_CURRENCY_SELECTOR_SCREEN_TOP_BAR_ACTION_BUTTON"
}