package com.tangem.core.ui.test

object ChooseNetworkBottomSheetTestTags {
    const val NETWORK_ITEM = "CHOOSE_NETWORK_BOTTOM_SHEET_NETWORK_ITEM"
    const val NETWORK_ICON = "CHOOSE_NETWORK_BOTTOM_SHEET_NETWORK_ICON"
    const val NETWORK_TITLE = "CHOOSE_NETWORK_BOTTOM_SHEET_NETWORK_TITLE"
    const val NETWORK_SUBTITLE = "CHOOSE_NETWORK_BOTTOM_SHEET_NETWORK_SUBTITLE"
}