package com.tangem.core.ui.test

object MainScreenTestTags {
    const val SCREEN_CONTAINER = "MAIN_SCREEN_CONTAINER"
    const val MORE_BUTTON = "MAIN_SCREEN_MORE_BUTTON"
    const val TOP_BAR = "MAIN_SCREEN_TOP_BAR"
    const val TOKEN_LIST_ITEM = "MAIN_SCREEN_TOKEN_LIST_ITEM"
    const val TOKEN_TITLE = "MAIN_SCREEN_TOKEN_TITLE"
    const val TOKEN_ICON = "MAIN_SCREEN_TOKEN_ICON"
    const val TOKEN_PRICE = "MAIN_SCREEN_TOKEN_PRICE"
    const val TOKEN_FIAT_AMOUNT = "MAIN_SCREEN_TOKEN_FIAT_AMOUNT"
    const val TOKEN_CRYPTO_AMOUNT = "MAIN_SCREEN_TOKEN_CRYPTO_AMOUNT"
    const val TOKEN_NO_ADDRESS = "MAIN_SCREEN_TOKEN_NO_ADDRESS"
    const val WALLET_BALANCE = "MAIN_SCREEN_WALLET_BALANCE"
    const val WALLET_LIST_ITEM = "MAIN_SCREEN_WALLET_LIST_ITEM"
}