package com.tangem.core.ui.test

object MainScreenTestTags {
    const val SCREEN_CONTAINER = "MAIN_SCREEN_CONTAINER"
    const val MORE_BUTTON = "MAIN_SCREEN_MORE_BUTTON"
    const val TOP_BAR = "MAIN_SCREEN_TOP_BAR"
    const val TOKEN_LIST_ITEM = "MAIN_SCREEN_TOKEN_LIST_ITEM"
    const val WALLET_LIST_ITEM = "MAIN_SCREEN_WALLET_LIST_ITEM"
    const val ORGANIZE_TOKENS_BUTTON = "MAIN_SCREEN_ORGANIZE_TOKENS_BUTTON"
    const val MULTI_CURRENCY_ACTION_BUTTON = "MAIN_SCREEN_MULTI_CURRENCY_ACTION_BUTTON"
    const val CARD_TITLE = "MAIN_SCREEN_CARD_TITLE"
    const val CARD_IMAGE = "MAIN_SCREEN_CARD_IMAGE"

    const val WALLET_BALANCE = "MAIN_SCREEN_WALLET_BALANCE"
    const val TOTAL_BALANCE_MENU_ITEM = "MAIN_SCREEN_TOTAL_BALANCE_MENU_ITEM"
    const val TOTAL_BALANCE_CONTAINER = "MAIN_SCREEN_TOTAL_BALANCE_CONTAINER"
}