package com.tangem.core.ui.test

object MarketsTestTags {
    const val TOKENS_LIST = "MARKETS_TOKENS_LIST"
    const val TOKENS_LIST_ITEM = "MARKETS_TOKENS_LIST_ITEM"
    const val TOKENS_LIST_ITEM_NAME = "MARKETS_TOKENS_LIST_ITEM_NAME"
    const val TOKENS_LIST_ITEM_PRICE_CHANGE = "MARKETS_TOKENS_LIST_ITEM_PRICE_CHANGE"
    const val LISTED_ON_EXCHANGES_COUNT = "MARKETS_LISTED_ON_EXCHANGES_COUNT"

    const val SEE_ALL_BUTTON = "MARKETS_SEE_ALL_BUTTON"

    const val SORT_BUTTON = "MARKETS_SORT_BUTTON"
    const val SORT_OPTION = "MARKETS_SORT_OPTION"
    const val INTERVAL_SEGMENT = "MARKETS_INTERVAL_SEGMENT"

    const val NO_RESULTS_LABEL = "MARKETS_NO_RESULTS_LABEL"
    const val SHOW_TOKENS_UNDER_CAP_BUTTON = "MARKETS_SHOW_TOKENS_UNDER_CAP_BUTTON"

    const val SECURITY_SCORE_BLOCK = "MARKETS_SECURITY_SCORE_BLOCK"
    const val SECURITY_SCORE_VALUE = "MARKETS_SECURITY_SCORE_VALUE"
    const val SECURITY_SCORE_REVIEWS_COUNT = "MARKETS_SECURITY_SCORE_REVIEWS_COUNT"
    const val SECURITY_SCORE_STARS = "MARKETS_SECURITY_SCORE_STARS"
    const val SECURITY_SCORE_INFO_BUTTON = "MARKETS_SECURITY_SCORE_INFO_BUTTON"
    const val SECURITY_SCORE_DETAILS_TITLE = "MARKETS_SECURITY_SCORE_DETAILS_TITLE"
    const val SECURITY_SCORE_DETAILS_PROVIDER_LINK = "MARKETS_SECURITY_SCORE_DETAILS_PROVIDER_LINK"
}