package com.tangem.core.ui.test

object MarketsTestTags {
    const val TOKENS_LIST = "MARKETS_TOKENS_LIST"
    const val TOKENS_LIST_ITEM = "MARKETS_TOKENS_LIST_ITEM"
    const val LISTED_ON_EXCHANGES_COUNT = "MARKETS_LISTED_ON_EXCHANGES_COUNT"
    const val LISTED_ON_BLOCK = "MARKETS_LISTED_ON_BLOCK"
    const val TOKEN_DETAILS_CONTENT = "MARKETS_TOKEN_DETAILS_CONTENT"
}