package com.tangem.core.ui.test

object MarketsTestTags {
    const val TOKENS_LIST = "MARKETS_TOKENS_LIST"
    const val TOKENS_LIST_ITEM = "MARKETS_TOKENS_LIST_ITEM"
    const val ADD_TO_PORTFOLIO_SWITCH = "MARKETS_ADD_TO_PORTFOLIO_SWITCH"
    const val LISTED_ON_EXCHANGES_COUNT = "MARKETS_LISTED_ON_EXCHANGES_COUNT"
}