package com.tangem.core.ui.test

object OnrampOffersBlockTestTags {
    const val PROVIDER_NAME = "ONRAMP_OFFERS_BLOCK_PROVIDER_TITLE"
    const val BEST_RATE_ICON = "ONRAMP_OFFERS_BLOCK_BEST_RATE_ICON"
    const val BEST_RATE_TITLE = "ONRAMP_OFFERS_BLOCK_BEST_RATE_TITLE"
    const val OFFER_TOKEN_AMOUNT = "ONRAMP_OFFERS_BLOCK_OFFER_TOKEN_AMOUNT"
    const val TIMING_ICON = "ONRAMP_OFFERS_BLOCK_TIMING_ICON"
    const val PAY_WITH = "ONRAMP_OFFERS_BLOCK_PAY_WITH"
    const val PAYMENT_METHOD_ICON = "ONRAMP_OFFERS_BLOCK_PAYMENT_METHOD_ICON"
    const val TIMING_TEXT = "ONRAMP_OFFERS_BLOCK_TIMING_TEXT"
}