package com.tangem.core.ui.test

object SelectSwapProviderBottomSheetTestTags {

    const val PROVIDER_NAME = "SELECT_SWAP_PROVIDER_BOTTOM_SHEET_PROVIDER_NAME"
    const val PROVIDER_TYPE = "SELECT_SWAP_PROVIDER_BOTTOM_SHEET_PROVIDER_TYPE"
    const val BEST_RATE_LABEL = "SELECT_SWAP_PROVIDER_BOTTOM_SHEET_BEST_RATE_LABEL"
    const val AMOUNT = "SELECT_SWAP_PROVIDER_BOTTOM_SHEET_AMOUNT"
    const val PROVIDER_ITEM = "SELECT_SWAP_PROVIDER_BOTTOM_SHEET_PROVIDER_ITEM"
}