package com.tangem.core.ui.test

object SelectNetworkFeeBottomSheetTestTags {
    const val REGULAR_FEE_ITEM = "SELECT_NETWORK_FEE_REGULAR_FEE_ITEM"
    const val REGULAR_ITEM_ICON = "SELECT_NETWORK_FEE_REGULAR_ITEM_ICON"
    const val REGULAR_ITEM_TITLE = "SELECT_NETWORK_FEE_REGULAR_ITEM_TITLE"
    const val DOT_SIGN = "SELECT_NETWORK_FEE_DOT_SIGN"
    const val TOKEN_AMOUNT = "SELECT_NETWORK_FEE_TOKEN_AMOUNT"
    const val FIAT_AMOUNT = "SELECT_NETWORK_FEE_FIAT_AMOUNT"
    const val LEARN_MORE_TEXT = "SELECT_NETWORK_FEE_LEARN_MORE_TEXT"

    const val CUSTOM_FEE_ITEM = "SELECT_NETWORK_FEE_CUSTOM_FEE_ITEM"
    const val CUSTOM_ITEM_ICON = "SELECT_NETWORK_FEE_CUSTOM_ITEM_ICON"
    const val CUSTOM_ITEM_TITLE = "SELECT_NETWORK_FEE_CUSTOM_ITEM_TITLE"

    const val CUSTOM_INPUT_ITEM = "SELECT_NETWORK_FEE_CUSTOM_INPUT_ITEM"
    const val NONCE_INPUT_ITEM = "SELECT_NETWORK_FEE_NONCE_INPUT_ITEM"
    const val NONCE_INPUT_TEXT_FIELD = "SELECT_NETWORK_FEE_NONCE_INPUT_TEXT_FIELD"
    const val CUSTOM_INPUT_ITEM_TITLE = "SELECT_NETWORK_FEE_CUSTOM_INPUT_ITEM_TITLE"
    const val CUSTOM_INPUT_ITEM_TOOLTIP_ICON = "SELECT_NETWORK_FEE_CUSTOM_INPUT_ITEM_TOOLTIP_ICON"
    const val CUSTOM_INPUT_ITEM_INPUT_TEXT_FIELD = "SELECT_NETWORK_FEE_CUSTOM_INPUT_ITEM_INPUT_TEXT_FIELD"
    const val CUSTOM_INPUT_ITEM_FIAT_AMOUNT = "SELECT_NETWORK_FEE_CUSTOM_INPUT_ITEM_FIAT_AMOUNT"
}