package com.tangem.core.ui.test

object SendConfirmScreenTestTags {
    const val SENDING_TEXT = "SEND_CONFIRM_SCREEN_SENDING_TEXT"
    const val RECIPIENT_ADDRESS = "SEND_CONFIRM_SCREEN_RECIPIENT_ADDRESS"
    const val BLOCKCHAIN_ADDRESS = "SEND_CONFIRM_SCREEN_BLOCKCHAIN_ADDRESS"
    const val RECIPIENT_ADDRESS_ICON = "SEND_CONFIRM_SCREEN_RECIPIENT_ADDRESS_ICON"
}