package com.tangem.core.ui.test

object SendScreenTestTags {
    const val SCREEN_CONTAINER = "SEND_SCREEN_CONTAINER"

    const val AMOUNT_CONTAINER_TITLE = "SEND_SCREEN_AMOUNT_CONTAINER_TITLE"
    const val INPUT_TEXT_FIELD = "SEND_SCREEN_INPUT_TEXT_FIELD"
    const val TOKEN_NAME = "SEND_SCREEN_TOKEN_NAME"
    const val PRIMARY_AMOUNT = "SEND_SCREEN_PRIMARY_AMOUNT"
    const val SECONDARY_AMOUNT = "SEND_SCREEN_SECONDARY_AMOUNT"

    const val MAX_BUTTON = "SEND_SCREEN_MAX_BUTTON"
    const val PREVIOUS_BUTTON = "SEND_SCREEN_PREVIOUS_BUTTON"
}