package com.tangem.core.ui.test

object SendConfirmScreenTestTags {
    const val SENDING_TEXT = "SEND_CONFIRM_SCREEN_SENDING_TEXT"
    const val RECIPIENT_ADDRESS = "SEND_CONFIRM_SCREEN_RECIPIENT_ADDRESS"
    const val BLOCKCHAIN_ADDRESS = "SEND_CONFIRM_SCREEN_BLOCKCHAIN_ADDRESS"
    const val RECIPIENT_ADDRESS_ICON = "SEND_CONFIRM_SCREEN_RECIPIENT_ADDRESS_ICON"
    const val PROVIDER_NAME = "SEND_CONFIRM_SCREEN_PROVIDER_NAME"
    const val BEST_RATE_BADGE = "SEND_CONFIRM_SCREEN_BEST_RATE_BADGE"
}