package com.tangem.core.ui.test

object SendScreenTestTags {
    const val SCREEN_CONTAINER = "SEND_SCREEN_CONTAINER"

    const val AMOUNT_CONTAINER_TITLE = "SEND_SCREEN_AMOUNT_CONTAINER_TITLE"
    const val AMOUNT_CONTAINER_TEXT = "SEND_SCREEN_AMOUNT_CONTAINER_TEXT"
    const val INPUT_TEXT_FIELD = "SEND_SCREEN_INPUT_TEXT_FIELD"
    const val SECONDARY_AMOUNT = "SEND_SCREEN_SECONDARY_AMOUNT"

    const val CURRENCY_BUTTON = "SEND_SCREEN_CURRENCY_BUTTON"
    const val FIAT_ICON = "SEND_SCREEN_FIAT_ICON"
    const val CURRENCY_ICON = "SEND_SCREEN_CURRENCY_ICON"
    const val MAX_BUTTON = "END_SCREEN_MAX_BUTTON"
    const val PREVIOUS_BUTTON = "SEND_SCREEN_PREVIOUS_BUTTON"
}