package com.tangem.core.ui.test

object SendScreenTestTags {
    const val SCREEN_CONTAINER = "SEND_SCREEN_CONTAINER"

    const val AMOUNT_CONTAINER_TITLE = "SEND_SCREEN_AMOUNT_CONTAINER_TITLE"
    const val INPUT_TEXT_FIELD = "SEND_SCREEN_INPUT_TEXT_FIELD"
    const val AMOUNT_ERROR_TEXT = "SEND_SCREEN_AMOUNT_ERROR_TEXT"
    const val EQUIVALENT_INPUT_AMOUNT = "SEND_SCREEN_EQUIVALENT_INPUT_AMOUNT"
    const val EXCHANGE_ICON = "SEND_SCREEN_EXCHANGE_ICON"
    const val TOKEN_NAME = "SEND_SCREEN_TOKEN_NAME"
    const val PRIMARY_AMOUNT = "SEND_SCREEN_PRIMARY_AMOUNT"
    const val SECONDARY_AMOUNT = "SEND_SCREEN_SECONDARY_AMOUNT"

    const val MAX_BUTTON = "SEND_SCREEN_MAX_BUTTON"
    const val PREVIOUS_BUTTON = "SEND_SCREEN_PREVIOUS_BUTTON"

    const val SWAP_TO_ANOTHER_TOKEN_BUTTON = "SEND_SCREEN_SWAP_TO_ANOTHER_TOKEN_BUTTON"
    const val SWAP_TOKEN_NAME = "SEND_SCREEN_SWAP_TOKEN_NAME"
    const val CLOSE_CONVERT_ICON = "SEND_SCREEN_CLOSE_CONVERT_ICON"
}