package com.tangem.core.ui.test

object StakingDetailsScreenTestTags {
    const val SCREEN_CONTAINER = "TOKEN_DETAILS_SCREEN_CONTAINER"

    const val BANNER_IMAGE = "TOKEN_DETAILS_SCREEN_BANNER_IMAGE"
    const val BANNER_TEXT = "TOKEN_DETAILS_SCREEN_BANNER_TEXT"

    const val PARAMETER_BLOCK = "STAKING_DETAILS_PARAMETER_BLOCK"
    const val PARAMETER_NAME = "STAKING_DETAILS_PARAMETER_NAME"
    const val PARAMETER_VALUE = "STAKING_DETAILS_PARAMETER_VALUE"
    const val TOS_TEXT = "STAKING_DETAILS_TOS_TEXT"

    const val ACTIVE_STAKING_BLOCK = "STAKING_DETAILS_ACTIVE_STAKING_BLOCK"
}