package com.tangem.core.ui.test

object StakingSendScreenTestTags {
    const val SCREEN_CONTAINER = "STAKING_SEND_SCREEN_CONTAINER"

    const val AMOUNT_CONTAINER_TITLE = "STAKING_SEND_SCREEN_AMOUNT_CONTAINER_TITLE"
    const val AMOUNT_CONTAINER_TEXT = "STAKING_SEND_SCREEN_AMOUNT_CONTAINER_TEXT"
    const val INPUT_TEXT_FIELD = "STAKING_SEND_SCREEN_INPUT_TEXT_FIELD"
    const val SECONDARY_AMOUNT = "STAKING_SEND_SCREEN_SECONDARY_AMOUNT"

    const val CURRENCY_BUTTON = "STAKING_SEND_SCREEN_CURRENCY_BUTTON"
    const val FIAT_ICON = "STAKING_SEND_SCREEN_FIAT_ICON"
    const val CURRENCY_ICON = "STAKING_SEND_SCREEN_CURRENCY_ICON"
    const val MAX_BUTTON = "STAKING_SEND_SCREEN_MAX_BUTTON"
    const val PREVIOUS_BUTTON = "STAKING_SEND_SCREEN_PREVIOUS_BUTTON"
}