package com.tangem.core.ui.test

object StoriesScreenTestTags {
    const val SCREEN_CONTAINER = "STORIES_SCREEN_CONTAINER"
    const val SCAN_BUTTON = "STORIES_SCREEN_SCAN_BUTTON"
    const val ORDER_BUTTON = "STORIES_SCREEN_ORDER_BUTTON"
    const val CREATE_NEW_WALLET_BUTTON = "STORIES_SCREEN_CREATE_NEW_WALLET_BUTTON"
    const val ADD_EXISTING_WALLET_BUTTON = "STORIES_SCREEN_ADD_EXISTING_WALLET_BUTTON"
}