package com.tangem.core.ui.test

object SwapTokenScreenTestTags {
    const val CONTAINER = "SWAP_TOKEN_SCREEN_CONTAINER"
    const val SWAP_BLOCK_HEADER = "SWAP_TOKEN_SCREEN_SWAP_BLOCK_HEADER"
    const val BALANCE = "SWAP_TOKEN_SCREEN_BALANCE"
    const val SWAP_TEXT_FIELD = "SWAP_TOKEN_SCREEN_SWAP_TEXT_FIELD"
    const val RECEIVE_TEXT_FIELD = "SWAP_TOKEN_SCREEN_RECEIVE_TEXT_FIELD"
    const val SWAP_CARD = "SWAP_TOKEN_SCREEN_SWAP_CARD"
    const val RECEIVE_CARD = "SWAP_TOKEN_SCREEN_RECEIVE_CARD"
    const val RECEIVE_AMOUNT_SHIMMER = "SWAP_TOKEN_SCREEN_RECEIVE_AMOUNT_SHIMMER"
    const val PROVIDERS_BLOCK = "SWAP_TOKEN_SCREEN_PROVIDERS_BLOCK"
    const val REPLACE_TOKENS_BUTTON = "SWAP_TOKEN_SCREEN_REPLACE_TOKENS_BUTTON"
    const val TOKEN = "SWAP_TOKEN_SCREEN_TOKEN"
    const val TOKEN_SYMBOL = "SWAP_TOKEN_SCREEN_TOKEN_SYMBOL"
    const val TOKEN_ICON = "SWAP_TOKEN_SCREEN_TOKEN_ICON"
    const val SELECT_TOKEN_ICON = "SWAP_TOKEN_SCREEN_SELECT_TOKEN_ICON"
    const val RECEIVE_FIAT_AMOUNT = "SWAP_TOKEN_SCREEN_RECEIVE_FIAT_AMOUNT"
    const val RECEIVE_FIAT_AMOUNT_INFORMATION_ICON = "SWAP_TOKEN_SCREEN_PRICE_IMPACT_INFORMATION_ICON"
    const val SWAP_FIAT_AMOUNT = "SWAP_TOKEN_SCREEN_SWAP_FIAT_AMOUNT"
}