package com.tangem.core.ui.test

object SwapTokenScreenTestTags {
    const val SWAP_BLOCK_HEADER = "SWAP_TOKEN_SCREEN_SWAP_BLOCK"
    const val BALANCE = "SWAP_TOKEN_SCREEN_BALANCE"
    const val SWAP_TEXT_FIELD = "SWAP_TOKEN_SCREEN_SWAP_TEXT_FIELD"
    const val RECEIVE_TEXT_FIELD = "SWAP_TOKEN_SCREEN_RECEIVE_TEXT_FIELD"
    const val RECEIVE_AMOUNT_SHIMMER = "SWAP_TOKEN_SCREEN_RECEIVE_AMOUNT_SHIMMER"
    const val NETWORK_FEE_BLOCK = "SWAP_TOKEN_SCREEN_NETWORK_FEE_BLOCK"
    const val PROVIDERS_BLOCK = "SWAP_TOKEN_SCREEN_PROVIDERS_BLOCK"
    const val SWAP_BUTTON = "SWAP_TOKEN_SCREEN_SWAP_BUTTON"
    const val TOKEN = "SWAP_TOKEN_SCREEN_TOKEN"
    const val TOKEN_NAME = "SWAP_TOKEN_SCREEN_TOKEN_NAME"
    const val TOKEN_ICON = "SWAP_TOKEN_SCREEN_TOKEN_ICON"
}