package com.tangem.core.ui.test

object TangemPayTestTags {
    // Main wallet screen tile (entry point into Tangem Pay)
    const val MAIN_SCREEN_TILE = "TANGEM_PAY_MAIN_SCREEN_TILE"

    // Payment account details screen
    const val PAYMENT_ACCOUNT_BALANCE = "TANGEM_PAY_PAYMENT_ACCOUNT_BALANCE"
    const val PAYMENT_ACCOUNT_CARD_BUTTON = "TANGEM_PAY_PAYMENT_ACCOUNT_CARD_BUTTON"

    // Card details (reveal + copy)
    const val CARD_DETAILS_SHOW_BUTTON = "TANGEM_PAY_CARD_DETAILS_SHOW_BUTTON"
    const val CARD_DETAILS_HIDE_BUTTON = "TANGEM_PAY_CARD_DETAILS_HIDE_BUTTON"
    const val CARD_DETAILS_NUMBER_VALUE = "TANGEM_PAY_CARD_DETAILS_NUMBER_VALUE"
    const val CARD_DETAILS_EXPIRATION_VALUE = "TANGEM_PAY_CARD_DETAILS_EXPIRATION_VALUE"
    const val CARD_DETAILS_CVC_VALUE = "TANGEM_PAY_CARD_DETAILS_CVC_VALUE"
    const val CARD_DETAILS_COPY_NUMBER = "TANGEM_PAY_CARD_DETAILS_COPY_NUMBER"
    const val CARD_DETAILS_COPY_EXPIRATION = "TANGEM_PAY_CARD_DETAILS_COPY_EXPIRATION"
    const val CARD_DETAILS_COPY_CVC = "TANGEM_PAY_CARD_DETAILS_COPY_CVC"

    // Card management (card page settings)
    const val CHANGE_PIN_ROW = "TANGEM_PAY_CHANGE_PIN_ROW"
    const val FREEZE_CARD_ROW = "TANGEM_PAY_FREEZE_CARD_ROW"
    const val CARD_FROZEN_BADGE = "TANGEM_PAY_CARD_FROZEN_BADGE"

    // Freeze confirmation bottom sheet
    const val FREEZE_CONFIRMATION_SUBMIT_BUTTON = "TANGEM_PAY_FREEZE_CONFIRMATION_SUBMIT_BUTTON"

    // PIN entry screen
    const val PIN_SCREEN_TITLE = "TANGEM_PAY_PIN_SCREEN_TITLE"
    const val PIN_SCREEN_DESCRIPTION = "TANGEM_PAY_PIN_SCREEN_DESCRIPTION"
    const val PIN_INPUT_FIELD = "TANGEM_PAY_PIN_INPUT_FIELD"
    const val PIN_SUBMIT_BUTTON = "TANGEM_PAY_PIN_SUBMIT_BUTTON"
    const val PIN_ERROR_MESSAGE = "TANGEM_PAY_PIN_ERROR_MESSAGE"

    // PIN success screen
    const val PIN_SUCCESS_TITLE = "TANGEM_PAY_PIN_SUCCESS_TITLE"
    const val PIN_SUCCESS_DESCRIPTION = "TANGEM_PAY_PIN_SUCCESS_DESCRIPTION"
    const val PIN_DONE_BUTTON = "TANGEM_PAY_PIN_DONE_BUTTON"
}