package com.tangem.core.ui.test

object TangemPayTestTags {
    // Main wallet screen tile (entry point into Tangem Pay)
    const val MAIN_SCREEN_TILE = "TANGEM_PAY_MAIN_SCREEN_TILE"

    // Payment account details screen
    const val PAYMENT_ACCOUNT_BALANCE = "TANGEM_PAY_PAYMENT_ACCOUNT_BALANCE"
    const val PAYMENT_ACCOUNT_CARD_BUTTON = "TANGEM_PAY_PAYMENT_ACCOUNT_CARD_BUTTON"

    // Card details (reveal + copy)
    const val CARD_DETAILS_SHOW_BUTTON = "TANGEM_PAY_CARD_DETAILS_SHOW_BUTTON"
    const val CARD_DETAILS_HIDE_BUTTON = "TANGEM_PAY_CARD_DETAILS_HIDE_BUTTON"
    const val CARD_DETAILS_NUMBER_VALUE = "TANGEM_PAY_CARD_DETAILS_NUMBER_VALUE"
    const val CARD_DETAILS_EXPIRATION_VALUE = "TANGEM_PAY_CARD_DETAILS_EXPIRATION_VALUE"
    const val CARD_DETAILS_CVC_VALUE = "TANGEM_PAY_CARD_DETAILS_CVC_VALUE"
    const val CARD_DETAILS_COPY_NUMBER = "TANGEM_PAY_CARD_DETAILS_COPY_NUMBER"
    const val CARD_DETAILS_COPY_EXPIRATION = "TANGEM_PAY_CARD_DETAILS_COPY_EXPIRATION"
    const val CARD_DETAILS_COPY_CVC = "TANGEM_PAY_CARD_DETAILS_COPY_CVC"

    // Card management (card page settings)
    const val SHOW_DETAILS_ROW = "TANGEM_PAY_SHOW_DETAILS_ROW"
    const val CHANGE_PIN_ROW = "TANGEM_PAY_CHANGE_PIN_ROW"
    const val FREEZE_CARD_ROW = "TANGEM_PAY_FREEZE_CARD_ROW"
    const val CARD_FROZEN_BADGE = "TANGEM_PAY_CARD_FROZEN_BADGE"

    // Card page top bar more-actions menu (redesign)
    const val CARD_PAGE_MORE_BUTTON = "TANGEM_PAY_CARD_PAGE_MORE_BUTTON"

    // Masked card number shown on the card face (e.g. "*4242")
    const val CARD_NUMBER_SHORT = "TANGEM_PAY_CARD_NUMBER_SHORT"

    // Replace card (reissue) bottom sheet
    const val REISSUE_SHEET_CONFIRM_BUTTON = "TANGEM_PAY_REISSUE_SHEET_CONFIRM_BUTTON"
    const val REISSUE_SHEET_FEE_VALUE = "TANGEM_PAY_REISSUE_SHEET_FEE_VALUE"

    // Transaction details bottom sheet
    const val TRANSACTION_DETAILS_AMOUNT = "TANGEM_PAY_TRANSACTION_DETAILS_AMOUNT"

    // Freeze confirmation bottom sheet
    const val FREEZE_CONFIRMATION_SUBMIT_BUTTON = "TANGEM_PAY_FREEZE_CONFIRMATION_SUBMIT_BUTTON"

    // PIN entry screen
    const val PIN_SCREEN_TITLE = "TANGEM_PAY_PIN_SCREEN_TITLE"
    const val PIN_SCREEN_DESCRIPTION = "TANGEM_PAY_PIN_SCREEN_DESCRIPTION"
    const val PIN_INPUT_FIELD = "TANGEM_PAY_PIN_INPUT_FIELD"
    const val PIN_SUBMIT_BUTTON = "TANGEM_PAY_PIN_SUBMIT_BUTTON"
    const val PIN_ERROR_MESSAGE = "TANGEM_PAY_PIN_ERROR_MESSAGE"

    // PIN success screen
    const val PIN_SUCCESS_TITLE = "TANGEM_PAY_PIN_SUCCESS_TITLE"
    const val PIN_SUCCESS_DESCRIPTION = "TANGEM_PAY_PIN_SUCCESS_DESCRIPTION"
    const val PIN_DONE_BUTTON = "TANGEM_PAY_PIN_DONE_BUTTON"

    // Daily limit block (card page)
    const val DAILY_LIMIT_CHANGE_BUTTON = "TANGEM_PAY_DAILY_LIMIT_CHANGE_BUTTON"
    const val DAILY_LIMIT_CURRENT_VALUE = "TANGEM_PAY_DAILY_LIMIT_CURRENT_VALUE"

    // Daily limit setup screen (amount field reuses SendScreenTestTags.INPUT_TEXT_FIELD from AmountTextField)
    const val DAILY_LIMIT_HINT = "TANGEM_PAY_DAILY_LIMIT_HINT"
    const val DAILY_LIMIT_SET_BUTTON = "TANGEM_PAY_DAILY_LIMIT_SET_BUTTON"

    // Daily limit success screen
    const val DAILY_LIMIT_SUCCESS_TITLE = "TANGEM_PAY_DAILY_LIMIT_SUCCESS_TITLE"
    const val DAILY_LIMIT_DONE_BUTTON = "TANGEM_PAY_DAILY_LIMIT_DONE_BUTTON"

    fun dailyLimitPresetChip(rawValue: String): String = "TANGEM_PAY_DAILY_LIMIT_PRESET_$rawValue"
}