package com.tangem.core.ui.test

object TestTags {
    const val STORIES_SCREEN = "STORIES_SCREEN_CONTAINER"
    const val STORIES_SCREEN_SCAN_BUTTON = "STORIES_SCREEN_SCAN_BUTTON"
    const val STORIES_SCREEN_ORDER_BUTTON = "STORIES_SCREEN_ORDER_BUTTON"

    const val MAIN_SCREEN = "MAIN_SCREEN_CONTAINER"
    const val MAIN_SCREEN_MORE_BUTTON = "MAIN_SCREEN_MORE_BUTTON"
    const val MAIN_SCREEN_TOP_BAR = "MAIN_SCREEN_TOP_BAR"

    const val DETAILS_SCREEN = "DETAILS_SCREEN_CONTAINER"
    const val DETAILS_SCREEN_ITEM = "DETAILS_SCREEN_ITEM"

    const val WALLET_SETTINGS_SCREEN = "WALLET_SETTINGS_SCREEN"
    const val WALLET_SETTINGS_SCREEN_ITEM = "WALLET_SETTINGS_SCREEN_ITEM"

    const val DISCLAIMER_SCREEN_CONTAINER = "DISCLAIMER_SCREEN_CONTAINER"
    const val DISCLAIMER_SCREEN_ACCEPT_BUTTON = "DISCLAIMER_SCREEN_ACCEPT_BUTTON"
}