package com.tangem.core.ui.test

object TokenDetailsScreenTestTags {
    const val SCREEN_CONTAINER = "TOKEN_DETAILS_SCREEN_CONTAINER"
    const val TOKEN_TITLE = "TOKEN_DETAILS_SCREEN_TOKEN_TITLE"
    const val ACTION_BUTTON = "TOKEN_DETAILS_SCREEN_ACTION_BUTTON"
    const val HORIZONTAL_ACTION_CHIPS = "TOKEN_DETAILS_SCREEN_HORIZONTAL_ACTION_CHIPS"
}