package com.tangem.core.ui.test

object TokenDetailsScreenTestTags {
    const val SCREEN_CONTAINER = "TOKEN_DETAILS_SCREEN_CONTAINER"

    const val TOKEN_TITLE = "TOKEN_DETAILS_SCREEN_TOKEN_TITLE"
    const val ACTION_BUTTON = "TOKEN_DETAILS_SCREEN_ACTION_BUTTON"
    const val HORIZONTAL_ACTION_CHIPS = "TOKEN_DETAILS_SCREEN_HORIZONTAL_ACTION_CHIPS"

    const val STAKING_BLOCK = "TOKEN_DETAILS_SCREEN_STAKING_BLOCK"
    const val STAKING_AVAILABLE_BLOCK = "TOKEN_DETAILS_SCREEN_STAKING_AVAILABLE_BLOCK"
    const val STAKING_CURRENCY_ICON = "TOKEN_DETAILS_SCREEN_STAKING_STAKING_CURRENCY_ICON"
    const val STAKING_SERVICE_TITLE = "TOKEN_DETAILS_SCREEN_STAKING_STAKING_SERVICE_TITLE"
    const val STAKING_SERVICE_TEXT = "TOKEN_DETAILS_SCREEN_STAKING_STAKING_SERVICE_TEXT"
    const val STAKING_FIAT_AMOUNT = "TOKEN_DETAILS_SCREEN_STAKING_FIAT_AMOUNT"
    const val STAKING_DOT = "TOKEN_DETAILS_SCREEN_STAKING_DOT"
    const val STAKING_TOKEN_AMOUNT = "TOKEN_DETAILS_SCREEN_STAKING_TOKEN_AMOUNT"
    const val STAKING_REWARD_VALUE = "TOKEN_DETAILS_SCREEN_STAKING_REWARD_VALUE"
    const val STAKING_CHEVRON_ICON = "TOKEN_DETAILS_SCREEN_STAKING_CHEVRON_ICON"
}