package com.tangem.core.ui.test

object TransactionSuccessScreenTestTags {
    const val CONTAINER = "TRANSACTION_SUCCESS_SCREEN_CONTAINER"
    const val TITLE = "TRANSACTION_SUCCESS_SCREEN_TITLE"
    const val TRANSACTION_DATE = "TRANSACTION_SUCCESS_SCREEN_DATE"
    const val AMOUNT_BLOCK = "TRANSACTION_SUCCESS_SCREEN_AMOUNT_BLOCK"
    const val FEE_BLOCK = "TRANSACTION_SUCCESS_SCREEN_FEE_BLOCK"
    const val PROVIDER_BLOCK = "TRANSACTION_SUCCESS_SCREEN_PROVIDER_BLOCK"
    const val RECIPIENT_BLOCK = "TRANSACTION_SUCCESS_SCREEN_RECIPIENT_BLOCK"
}