package com.tangem.core.ui.test

object WalletConnectScreenTestTags {
    const val EMPTY_SCREEN_IMAGE = "WALLET_CONNECT_EMPTY_SCREEN_IMAGE"
    const val EMPTY_SCREEN_TEXT = "WALLET_CONNECT_EMPTY_SCREEN_TEXT"
    const val SESSIONS_LAZY_LIST = "WALLET_CONNECT_SESSIONS_LAZY_LIST"
    const val SESSION_TITLE = "WALLET_CONNECT_SESSION_TEXT"
    const val CLOSE_SESSION_BUTTON = "WALLET_CONNECT_CLOSE_SESSION_BUTTON"
    const val ADD_SESSION_BUTTON = "WALLET_CONNECT_ADD_SESSION_BUTTON"
}