package com.tangem.core.ui.test

object WalletConnectScreenTestTags {
    const val EMPTY_SCREEN_IMAGE = "WALLET_CONNECT_EMPTY_SCREEN_IMAGE"
    const val EMPTY_SCREEN_TEXT = "WALLET_CONNECT_EMPTY_SCREEN_TEXT"
    const val SESSIONS_LAZY_LIST = "WALLET_CONNECT_SESSIONS_LAZY_LIST"
    const val SESSION_TITLE = "WALLET_CONNECT_SESSION_TEXT"
    const val CLOSE_SESSION_BUTTON = "WALLET_CONNECT_CLOSE_SESSION_BUTTON"
    const val ADD_SESSION_BUTTON = "WALLET_CONNECT_ADD_SESSION_BUTTON"

    const val MORE_BUTTON = "WALLET_CONNECT_SCREEN_MORE_BUTTON"
    const val WALLET_NAME = "WALLET_CONNECT_SCREEN_WALLET_NAME"
    const val APP_ICON = "WALLET_CONNECT_SCREEN_APP_ICON"
    const val APP_NAME = "WALLET_CONNECT_SCREEN_APP_NAME"
    const val APPROVE_ICON = "WALLET_CONNECT_SCREEN_APPROVE_ICON"
    const val APP_URL = "WALLET_CONNECT_SCREEN_APP_URL"
}