package com.tangem.core.ui.test

object WalletConnectBottomSheetTestTags {
    const val TITLE = "WALLET_CONNECT_BOTTOM_SHEET_TITLE"
    const val APP_ICON = "WALLET_CONNECT_BOTTOM_SHEET_APP_ICON"
    const val APP_NAME = "WALLET_CONNECT_BOTTOM_SHEET_APP_NAME"
    const val APPROVE_ICON = "WALLET_CONNECT_BOTTOM_SHEET_APPROVE_ICON"
    const val APP_URL = "WALLET_CONNECT_BOTTOM_SHEET_APP_URL"

    const val CONNECTION_REQUEST_ICON = "WALLET_CONNECT_BOTTOM_SHEET_CONNECTION_REQUEST_ICON"
    const val CONNECTION_REQUEST_TEXT = "WALLET_CONNECT_BOTTOM_SHEET_CONNECTION_REQUEST_TEXT"
    const val CONNECTION_REQUEST_CHEVRON = "WALLET_CONNECT_BOTTOM_SHEET_CONNECTION_REQUEST_CHEVRON"

    const val WALLET_ICON = "WALLET_CONNECT_BOTTOM_SHEET_WALLET_ICON"
    const val WALLET_NAME_TITLE = "WALLET_CONNECT_BOTTOM_SHEET_WALLET_NAME_TITLE"
    const val WALLET_NAME = "WALLET_CONNECT_BOTTOM_SHEET_WALLET_NAME"

    const val NETWORKS_ICON = "WALLET_CONNECT_BOTTOM_SHEET_NETWORKS_ICON"
    const val NETWORKS_TITLE = "WALLET_CONNECT_BOTTOM_SHEET_NETWORKS_TITLE"
    const val NETWORKS_SELECTOR_ICON = "WALLET_CONNECT_BOTTOM_SHEET_NETWORKS_SELECTOR_ICON"
    const val NETWORKS_ICONS = "WALLET_CONNECT_BOTTOM_SHEET_NETWORKS_ICONS"
}