package com.tangem.core.ui.test

object WalletConnectDetailsBottomSheetTestTags {
    const val TITLE = "WALLET_CONNECT_DETAILS_BOTTOM_SHEET_TITLE"
    const val DATE = "WALLET_CONNECT_DETAILS_BOTTOM_SHEET_DATE"
    const val CLOSE_BUTTON = "WALLET_CONNECT_DETAILS_BOTTOM_CLOSE_BUTTON"
    const val DISCONNECT_BUTTON = "WALLET_CONNECT_DETAILS_BOTTOM_SHEET_DISCONNECT_BUTTON"
    const val WALLET_ICON = "WALLET_CONNECT_DETAILS_BOTTOM_WALLET_ICON"
    const val WALLET_TITLE = "WALLET_CONNECT_DETAILS_BOTTOM_WALLET"
    const val WALLET_NAME = "WALLET_CONNECT_DETAILS_BOTTOM_WALLET_NAME"
    const val NETWORKS_TITLE = "WALLET_CONNECT_DETAILS_BOTTOM_WALLET_NAME"
    const val NETWORK_ITEM = "WALLET_CONNECT_DETAILS_BOTTOM_SHEET_NETWORK_ITEM"
    const val NETWORK_ICON = "WALLET_CONNECT_DETAILS_BOTTOM_SHEET_NETWORK_ICON"
    const val NETWORK_NAME = "WALLET_CONNECT_DETAILS_BOTTOM_SHEET_NETWORK_NAME"
    const val NETWORK_SYMBOL = "WALLET_CONNECT_DETAILS_BOTTOM_SHEET_NETWORK_SYMBOL"
}