package com.tangem.core.ui.test

object WarningBottomSheetTestTags {
    const val ICON = "BASE_WARNING_BOTTOM_SHEET_ICON"
    const val TITLE = "BASE_WARNING_BOTTOM_SHEET_TITLE"
    const val MESSAGE = "BASE_WARNING_BOTTOM_SHEET_MESSAGE"
    const val BUTTON_PRIMARY = "BASE_WARNING_BOTTOM_SHEET_BUTTON_PRIMARY"
    const val BUTTON_SECONDARY = "BASE_WARNING_BOTTOM_SHEET_BUTTON_SECONDARY"
}