package com.tangem.core.ui.test

object YieldSupplyTestTags {
    const val PROMO_CONTINUE_BUTTON = "YIELD_SUPPLY_PROMO_CONTINUE_BUTTON"
    const val START_EARNING_BUTTON = "YIELD_SUPPLY_START_EARNING_BUTTON"
    const val STOP_EARNING_BUTTON = "YIELD_SUPPLY_STOP_EARNING_BUTTON"
    const val STOP_EARNING_CONFIRM_BUTTON = "YIELD_SUPPLY_STOP_EARNING_CONFIRM_BUTTON"
    const val APPROVE_CONFIRM_BUTTON = "YIELD_SUPPLY_APPROVE_CONFIRM_BUTTON"
}