package com.tangem.core.ui.test.accounts

object AccountDetailsScreenTestTags {

    const val ACCOUNT_DETAILS_CONTAINER = "ACCOUNT_DETAILS_SCREEN_CONTAINER"
    const val MANAGE_TOKENS_BUTTON = "ACCOUNT_DETAILS_SCREEN_MANAGE_TOKENS_BUTTON"
    const val MEMBERS_BUTTON = "ACCOUNT_DETAILS_SCREEN_MEMBERS_BUTTON"
    const val NETWORKS_INFO = "ACCOUNT_DETAILS_SCREEN_NETWORKS_INFO"
    const val EDIT_ACCOUNT_BUTTON = "ACCOUNT_DETAILS_SCREEN_EDIT_ACCOUNT_BUTTON"
    const val ARCHIVE_ACCOUNT_BUTTON = "ACCOUNT_DETAILS_SCREEN_ARCHIVE_ACCOUNT_BUTTON"
}