package com.tangem.core.ui.test.accounts

object AccountInfoEditScreenTestTags {
    const val ACCOUNT_DETAILS_CONTAINER = "ACCOUNT_DETAILS_CONTAINER"
    const val ADD_ACCOUNT_BUTTON = "ADD_ACCOUNT_BUTTON"
    const val ACCOUNT_INFO_COLOR_OPTION = "ACCOUNT_INFO_COLOR_OPTION"
    const val ACCOUNT_INFO_TYPE_OPTION = "ACCOUNT_INFO_TYPE_OPTION"
    const val ACCOUNT_INFO_SELECTED_ICON = "ACCOUNT_INFO_CURRENT_ICON"
    const val ACCOUNT_INFO_NAME_FIELD = "ACCOUNT_INFO_NAME_FIELD"
}