package com.tangem.domain.common.configs

import com.tangem.blockchain.common.Blockchain
import com.tangem.common.card.EllipticCurve
import junit.framework.TestCase.assertEquals
import org.junit.Test

class Wallet2CardConfigTest {

    private val wallet2CardConfig = Wallet2CardConfig
    private val expectedMapping = mapOf(
        Blockchain.Unknown to null,
        Blockchain.Arbitrum to EllipticCurve.Secp256k1,
        Blockchain.ArbitrumTestnet to EllipticCurve.Secp256k1,
        Blockchain.Avalanche to EllipticCurve.Secp256k1,
        Blockchain.AvalancheTestnet to EllipticCurve.Secp256k1,
        Blockchain.Binance to EllipticCurve.Secp256k1,
        Blockchain.BinanceTestnet to EllipticCurve.Secp256k1,
        Blockchain.BSC to EllipticCurve.Secp256k1,
        Blockchain.BSCTestnet to EllipticCurve.Secp256k1,
        Blockchain.Bitcoin to EllipticCurve.Secp256k1,
        Blockchain.BitcoinTestnet to EllipticCurve.Secp256k1,
        Blockchain.BitcoinCash to EllipticCurve.Secp256k1,
        Blockchain.BitcoinCashTestnet to EllipticCurve.Secp256k1,
        Blockchain.Cardano to EllipticCurve.Ed25519,
        Blockchain.Cosmos to EllipticCurve.Secp256k1,
        Blockchain.CosmosTestnet to EllipticCurve.Secp256k1,
        Blockchain.Dogecoin to EllipticCurve.Secp256k1,
        Blockchain.Ducatus to EllipticCurve.Secp256k1,
        Blockchain.Ethereum to EllipticCurve.Secp256k1,
        Blockchain.EthereumTestnet to EllipticCurve.Secp256k1,
        Blockchain.EthereumClassic to EllipticCurve.Secp256k1,
        Blockchain.EthereumClassicTestnet to EllipticCurve.Secp256k1,
        Blockchain.Fantom to EllipticCurve.Secp256k1,
        Blockchain.FantomTestnet to EllipticCurve.Secp256k1,
        Blockchain.Litecoin to EllipticCurve.Secp256k1,
        Blockchain.Near to EllipticCurve.Ed25519Slip0010,
        Blockchain.NearTestnet to EllipticCurve.Ed25519Slip0010,
        Blockchain.Polkadot to EllipticCurve.Ed25519Slip0010,
        Blockchain.PolkadotTestnet to EllipticCurve.Ed25519Slip0010,
        Blockchain.Kava to EllipticCurve.Secp256k1,
        Blockchain.KavaTestnet to EllipticCurve.Secp256k1,
        Blockchain.Kusama to EllipticCurve.Ed25519Slip0010,
        Blockchain.Polygon to EllipticCurve.Secp256k1,
        Blockchain.PolygonTestnet to EllipticCurve.Secp256k1,
        Blockchain.RSK to EllipticCurve.Secp256k1,
        Blockchain.Sei to EllipticCurve.Secp256k1,
        Blockchain.SeiTestnet to EllipticCurve.Secp256k1,
        Blockchain.Stellar to EllipticCurve.Ed25519Slip0010,
        Blockchain.StellarTestnet to EllipticCurve.Ed25519Slip0010,
        Blockchain.Solana to EllipticCurve.Ed25519Slip0010,
        Blockchain.SolanaTestnet to EllipticCurve.Ed25519Slip0010,
        Blockchain.Tezos to EllipticCurve.Ed25519Slip0010,
        Blockchain.Tron to EllipticCurve.Secp256k1,
        Blockchain.TronTestnet to EllipticCurve.Secp256k1,
        Blockchain.XRP to EllipticCurve.Secp256k1,
        Blockchain.Gnosis to EllipticCurve.Secp256k1,
        Blockchain.Dash to EllipticCurve.Secp256k1,
        Blockchain.Optimism to EllipticCurve.Secp256k1,
        Blockchain.OptimismTestnet to EllipticCurve.Secp256k1,
        Blockchain.Dischain to EllipticCurve.Secp256k1,
        Blockchain.EthereumPow to EllipticCurve.Secp256k1,
        Blockchain.EthereumPowTestnet to EllipticCurve.Secp256k1,
        Blockchain.Kaspa to EllipticCurve.Secp256k1,
        Blockchain.Telos to EllipticCurve.Secp256k1,
        Blockchain.TelosTestnet to EllipticCurve.Secp256k1,
        Blockchain.TON to EllipticCurve.Ed25519Slip0010,
        Blockchain.TONTestnet to EllipticCurve.Ed25519Slip0010,
        Blockchain.Ravencoin to EllipticCurve.Secp256k1,
        Blockchain.RavencoinTestnet to EllipticCurve.Secp256k1,
        Blockchain.TerraV1 to EllipticCurve.Secp256k1,
        Blockchain.TerraV2 to EllipticCurve.Secp256k1,
        Blockchain.Cronos to EllipticCurve.Secp256k1,
        Blockchain.AlephZero to EllipticCurve.Ed25519Slip0010,
        Blockchain.AlephZeroTestnet to EllipticCurve.Ed25519Slip0010,
        Blockchain.OctaSpace to EllipticCurve.Secp256k1,
        Blockchain.OctaSpaceTestnet to EllipticCurve.Secp256k1,
        Blockchain.Chia to EllipticCurve.Bls12381G2Aug,
        Blockchain.ChiaTestnet to EllipticCurve.Bls12381G2Aug,
        Blockchain.Decimal to EllipticCurve.Secp256k1,
        Blockchain.DecimalTestnet to EllipticCurve.Secp256k1,
        Blockchain.XDC to EllipticCurve.Secp256k1,
        Blockchain.XDCTestnet to EllipticCurve.Secp256k1,
        Blockchain.VeChain to EllipticCurve.Secp256k1,
        Blockchain.VeChainTestnet to EllipticCurve.Secp256k1,
        Blockchain.Aptos to EllipticCurve.Ed25519Slip0010,
        Blockchain.AptosTestnet to EllipticCurve.Ed25519Slip0010,
        Blockchain.Playa3ull to EllipticCurve.Secp256k1,
        Blockchain.Shibarium to EllipticCurve.Secp256k1,
        Blockchain.ShibariumTestnet to EllipticCurve.Secp256k1,
        Blockchain.Algorand to EllipticCurve.Ed25519Slip0010,
        Blockchain.AlgorandTestnet to EllipticCurve.Ed25519Slip0010,
        Blockchain.Hedera to EllipticCurve.Ed25519Slip0010,
        Blockchain.HederaTestnet to EllipticCurve.Ed25519Slip0010,
        Blockchain.Aurora to EllipticCurve.Secp256k1,
        Blockchain.AuroraTestnet to EllipticCurve.Secp256k1,
        Blockchain.Areon to EllipticCurve.Secp256k1,
        Blockchain.AreonTestnet to EllipticCurve.Secp256k1,
        Blockchain.PulseChain to EllipticCurve.Secp256k1,
        Blockchain.PulseChainTestnet to EllipticCurve.Secp256k1,
        Blockchain.ZkSyncEra to EllipticCurve.Secp256k1,
        Blockchain.ZkSyncEraTestnet to EllipticCurve.Secp256k1,
        Blockchain.Nexa to EllipticCurve.Secp256k1,
        Blockchain.NexaTestnet to EllipticCurve.Secp256k1,
        Blockchain.Moonbeam to EllipticCurve.Secp256k1,
        Blockchain.MoonbeamTestnet to EllipticCurve.Secp256k1,
        Blockchain.Manta to EllipticCurve.Secp256k1,
        Blockchain.MantaTestnet to EllipticCurve.Secp256k1,
        Blockchain.PolygonZkEVM to EllipticCurve.Secp256k1,
        Blockchain.PolygonZkEVMTestnet to EllipticCurve.Secp256k1,
        Blockchain.Radiant to EllipticCurve.Secp256k1,
        Blockchain.Base to EllipticCurve.Secp256k1,
        Blockchain.BaseTestnet to EllipticCurve.Secp256k1,
        Blockchain.Moonriver to EllipticCurve.Secp256k1,
        Blockchain.MoonriverTestnet to EllipticCurve.Secp256k1,
        Blockchain.Mantle to EllipticCurve.Secp256k1,
        Blockchain.MantleTestnet to EllipticCurve.Secp256k1,
        Blockchain.Fact0rn to EllipticCurve.Secp256k1,
        Blockchain.Flare to EllipticCurve.Secp256k1,
        Blockchain.FlareTestnet to EllipticCurve.Secp256k1,
        Blockchain.Taraxa to EllipticCurve.Secp256k1,
        Blockchain.TaraxaTestnet to EllipticCurve.Secp256k1,
        Blockchain.Koinos to EllipticCurve.Secp256k1,
        Blockchain.KoinosTestnet to EllipticCurve.Secp256k1,
        Blockchain.Joystream to EllipticCurve.Ed25519Slip0010,
        Blockchain.Bittensor to EllipticCurve.Ed25519Slip0010,
        Blockchain.Filecoin to EllipticCurve.Secp256k1,
        Blockchain.Blast to EllipticCurve.Secp256k1,
        Blockchain.BlastTestnet to EllipticCurve.Secp256k1,
        Blockchain.Cyber to EllipticCurve.Secp256k1,
        Blockchain.CyberTestnet to EllipticCurve.Secp256k1,
        Blockchain.InternetComputer to EllipticCurve.Secp256k1,
        Blockchain.Sui to EllipticCurve.Ed25519Slip0010,
        Blockchain.SuiTestnet to EllipticCurve.Ed25519Slip0010,
        Blockchain.EnergyWebChain to EllipticCurve.Secp256k1,
        Blockchain.EnergyWebChainTestnet to EllipticCurve.Secp256k1,
        Blockchain.EnergyWebX to EllipticCurve.Ed25519Slip0010,
        Blockchain.EnergyWebXTestnet to EllipticCurve.Ed25519Slip0010,
        Blockchain.Casper to EllipticCurve.Secp256k1,
        Blockchain.CasperTestnet to EllipticCurve.Secp256k1,
        Blockchain.Core to EllipticCurve.Secp256k1,
        Blockchain.CoreTestnet to EllipticCurve.Secp256k1,
        Blockchain.Xodex to EllipticCurve.Secp256k1,
        Blockchain.Canxium to EllipticCurve.Secp256k1,
        Blockchain.Chiliz to EllipticCurve.Secp256k1,
        Blockchain.ChilizTestnet to EllipticCurve.Secp256k1,
        Blockchain.Clore to EllipticCurve.Secp256k1,
        Blockchain.VanarChain to EllipticCurve.Secp256k1,
        Blockchain.VanarChainTestnet to EllipticCurve.Secp256k1,
        Blockchain.OdysseyChain to EllipticCurve.Secp256k1,
        Blockchain.OdysseyChainTestnet to EllipticCurve.Secp256k1,
        Blockchain.Bitrock to EllipticCurve.Secp256k1,
        Blockchain.BitrockTestnet to EllipticCurve.Secp256k1,
        Blockchain.Sonic to EllipticCurve.Secp256k1,
        Blockchain.SonicTestnet to EllipticCurve.Secp256k1,
        Blockchain.ApeChain to EllipticCurve.Secp256k1,
        Blockchain.ApeChainTestnet to EllipticCurve.Secp256k1,
        Blockchain.KaspaTestnet to EllipticCurve.Secp256k1,
        Blockchain.Alephium to EllipticCurve.Secp256k1,
        Blockchain.AlephiumTestnet to EllipticCurve.Secp256k1,
        Blockchain.Scroll to EllipticCurve.Secp256k1,
        Blockchain.ScrollTestnet to EllipticCurve.Secp256k1,
        Blockchain.ZkLinkNova to EllipticCurve.Secp256k1,
        Blockchain.ZkLinkNovaTestnet to EllipticCurve.Secp256k1,
    )

    @Test
    fun blockchainCurveMappingTest() {
        Blockchain.entries.forEach {
            val resultCurve = wallet2CardConfig.primaryCurve(it)
            assertEquals(expectedMapping[it], resultCurve)
        }
    }
}