package com.tangem.blockchainsdk.utils

import com.tangem.blockchain.common.Blockchain
import com.tangem.domain.models.network.Network

/**
 * The kind of transaction extras (memo / destination tag) a [Blockchain] supports, mapped to the domain
 * [Network.TransactionExtrasType]. Single source of truth for both [com.tangem.data.common.network.NetworkFactory] and
 * any feature that needs to know whether an address on this chain can carry a memo/tag.
 */
@Suppress("LongMethod")
fun Blockchain.getSupportedTransactionExtras(): Network.TransactionExtrasType {
    return when (this) {
        Blockchain.XRP -> Network.TransactionExtrasType.DESTINATION_TAG
        Blockchain.Binance,
        Blockchain.TON,
        Blockchain.Cosmos,
        Blockchain.TerraV1,
        Blockchain.TerraV2,
        Blockchain.Stellar,
        Blockchain.Hedera,
        Blockchain.Algorand,
        Blockchain.Sei,
        Blockchain.InternetComputer,
        Blockchain.Casper,
        -> Network.TransactionExtrasType.MEMO
        // region Other blockchains
        Blockchain.Unknown,
        Blockchain.Alephium,
        Blockchain.AlephiumTestnet,
        Blockchain.Arbitrum,
        Blockchain.ArbitrumTestnet,
        Blockchain.Avalanche,
        Blockchain.AvalancheTestnet,
        Blockchain.BinanceTestnet,
        Blockchain.BSC,
        Blockchain.BSCTestnet,
        Blockchain.Bitcoin,
        Blockchain.BitcoinTestnet,
        Blockchain.BitcoinCash,
        Blockchain.BitcoinCashTestnet,
        Blockchain.Cardano,
        Blockchain.CosmosTestnet,
        Blockchain.Dogecoin,
        Blockchain.Ducatus,
        Blockchain.Ethereum,
        Blockchain.EthereumTestnet,
        Blockchain.EthereumClassic,
        Blockchain.EthereumClassicTestnet,
        Blockchain.Fantom,
        Blockchain.FantomTestnet,
        Blockchain.Litecoin,
        Blockchain.Near,
        Blockchain.NearTestnet,
        Blockchain.Polkadot,
        Blockchain.PolkadotTestnet,
        Blockchain.Kava,
        Blockchain.KavaTestnet,
        Blockchain.Kusama,
        Blockchain.Polygon,
        Blockchain.PolygonTestnet,
        Blockchain.RSK,
        Blockchain.SeiTestnet,
        Blockchain.StellarTestnet,
        Blockchain.Solana,
        Blockchain.SolanaTestnet,
        Blockchain.Tezos,
        Blockchain.Tron,
        Blockchain.TronTestnet,
        Blockchain.Gnosis,
        Blockchain.Dash,
        Blockchain.Optimism,
        Blockchain.OptimismTestnet,
        Blockchain.Dischain,
        Blockchain.EthereumPow,
        Blockchain.EthereumPowTestnet,
        Blockchain.Kaspa,
        Blockchain.KaspaTestnet,
        Blockchain.Telos,
        Blockchain.TelosTestnet,
        Blockchain.TONTestnet,
        Blockchain.Ravencoin,
        Blockchain.Clore,
        Blockchain.RavencoinTestnet,
        Blockchain.Cronos,
        Blockchain.AlephZero,
        Blockchain.AlephZeroTestnet,
        Blockchain.OctaSpace,
        Blockchain.OctaSpaceTestnet,
        Blockchain.Chia,
        Blockchain.ChiaTestnet,
        Blockchain.Decimal,
        Blockchain.DecimalTestnet,
        Blockchain.XDC,
        Blockchain.XDCTestnet,
        Blockchain.VeChain,
        Blockchain.VeChainTestnet,
        Blockchain.Aptos,
        Blockchain.AptosTestnet,
        Blockchain.Playa3ull,
        Blockchain.Shibarium,
        Blockchain.ShibariumTestnet,
        Blockchain.AlgorandTestnet,
        Blockchain.HederaTestnet,
        Blockchain.Aurora,
        Blockchain.AuroraTestnet,
        Blockchain.Areon,
        Blockchain.AreonTestnet,
        Blockchain.PulseChain,
        Blockchain.PulseChainTestnet,
        Blockchain.ZkSyncEra,
        Blockchain.ZkSyncEraTestnet,
        Blockchain.Nexa,
        Blockchain.NexaTestnet,
        Blockchain.Moonbeam,
        Blockchain.MoonbeamTestnet,
        Blockchain.Manta,
        Blockchain.MantaTestnet,
        Blockchain.PolygonZkEVM,
        Blockchain.PolygonZkEVMTestnet,
        Blockchain.Radiant,
        Blockchain.Fact0rn,
        Blockchain.Base,
        Blockchain.BaseTestnet,
        Blockchain.Moonriver,
        Blockchain.MoonriverTestnet,
        Blockchain.Mantle,
        Blockchain.MantleTestnet,
        Blockchain.Flare,
        Blockchain.FlareTestnet,
        Blockchain.Taraxa,
        Blockchain.TaraxaTestnet,
        Blockchain.Koinos,
        Blockchain.KoinosTestnet,
        Blockchain.Joystream,
        Blockchain.Bittensor,
        Blockchain.Filecoin,
        Blockchain.Blast,
        Blockchain.BlastTestnet,
        Blockchain.Cyber,
        Blockchain.CyberTestnet,
        Blockchain.Sui,
        Blockchain.SuiTestnet,
        Blockchain.EnergyWebChain,
        Blockchain.EnergyWebChainTestnet,
        Blockchain.EnergyWebX,
        Blockchain.EnergyWebXTestnet,
        Blockchain.CasperTestnet,
        Blockchain.Core,
        Blockchain.CoreTestnet,
        Blockchain.Xodex,
        Blockchain.Canxium,
        Blockchain.Chiliz,
        Blockchain.ChilizTestnet,
        Blockchain.VanarChain,
        Blockchain.VanarChainTestnet,
        Blockchain.OdysseyChain, Blockchain.OdysseyChainTestnet,
        Blockchain.Bitrock, Blockchain.BitrockTestnet,
        Blockchain.Sonic, Blockchain.SonicTestnet,
        Blockchain.ApeChain, Blockchain.ApeChainTestnet,
        Blockchain.Scroll, Blockchain.ScrollTestnet,
        Blockchain.ZkLinkNova, Blockchain.ZkLinkNovaTestnet,
        Blockchain.Pepecoin, Blockchain.PepecoinTestnet,
        Blockchain.Hyperliquid, Blockchain.HyperliquidTestnet,
        Blockchain.Quai, Blockchain.QuaiTestnet,
        Blockchain.Linea, Blockchain.LineaTestnet,
        Blockchain.ArbitrumNova,
        Blockchain.Plasma, Blockchain.PlasmaTestnet,
        Blockchain.Adi, Blockchain.AdiTestnet,
        Blockchain.SeiEvm, Blockchain.SeiEvmTestnet,
        Blockchain.Monad, Blockchain.MonadTestnet,
        -> Network.TransactionExtrasType.NONE
        // endregion
    }
}