name: Get Version Name

on:
  workflow_call:
    outputs:
      version_name:
        description: "Version name"
        value: ${{ jobs.get_version_name.outputs.version_name }}

jobs:
  get_version_name:
    name: Get Version Name
    runs-on: ubuntu-latest
    outputs:
      version_name: ${{ steps.get_version_name.outputs.versionName }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version name from branch name
        id: get_version_name
        run: |
          BRANCH=${{ github.ref_name }}
          
          if [[ "$BRANCH" =~ ^(releases|hotfix)/([0-9]+)\.([0-9]+)(\.[0-9]+)?$ ]]; then
            MAJOR=${BASH_REMATCH[2]}
            MINOR=${BASH_REMATCH[3]}
            PATCH=${BASH_REMATCH[4]:-.0}
            VERSION="${MAJOR}.${MINOR}${PATCH}"
          else
            ./ci_resources/find-latest-release-branch.sh origin/$BRANCH
            LATEST_BRANCH=$(< 'find-latest-release-branch.output')
          
            if [[ "$LATEST_BRANCH" =~ releases/([0-9]+)\.([0-9]+) ]]; then
              MAJOR=${BASH_REMATCH[1]}
              MINOR=${BASH_REMATCH[2]}
              NEW_MINOR=$((MINOR + 1))
              VERSION="${MAJOR}.${NEW_MINOR}.0"
            else
              echo "Failed to get version"
              exit 1
            fi
          fi
          
          echo "versionName=$VERSION"
          echo "versionName=$VERSION" >> $GITHUB_OUTPUT
