name: Prepare for build

on:
  workflow_call:
    inputs:
      initial_version_code:
        required: true
        type: number
      checkout_dexprotector_config:
        required: false
        type: boolean
        default: false
    outputs:
      version_name:
        description: "Version name"
        value: ${{ jobs.get_version_name.outputs.version_name }}
      version_code:
        description: "Version code"
        value: ${{ jobs.prepare.outputs.version_code }}
      jira_summary:
        description: "Jira summary"
        value: ${{ jobs.prepare.outputs.jira_summary }}

jobs:
  get_version_name:
    uses: ./.github/workflows/get_version_name.yml

  prepare:
    name: Prepare
    runs-on: [ self-hosted, active-android, build ]
    needs: get_version_name
    outputs:
      version_code: ${{ steps.get_version_code.outputs.versionCode }}
      jira_summary: ${{ steps.jira.outputs.summary }}
    steps:
      - name: Jira Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}

      - name: Get Jira Issue Number from Branch Name
        id: jira
        uses: tangem-developments/jira-action@master
        with:
          action: getBranchSummary
          branch-name: ${{ github.ref_name }}

      - name: Clean
        run: rm -rf *

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GH_MOBILE_PAT }}
          fetch-depth: 0

      - name: Checkout dexprotector config
        if: ${{ inputs.checkout_dexprotector_config == true }}
        uses: actions/checkout@v4
        with:
          repository: 'tangem-developments/private-app-config'
          ref: 'main'
          token: ${{ secrets.GH_MOBILE_PAT }}
          path: 'app-config'

      - name: Increment version code
        id: get_version_code
        env:
          RUN_NUMBER: ${{ github.run_number }}
          INITIAL_VERSION_CODE: ${{ inputs.initial_version_code }}
        run: |
          VERSION_CODE=$((RUN_NUMBER + INITIAL_VERSION_CODE))
          echo "versionCode=$VERSION_CODE" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build --platform linux/arm64 -t tangem_ci_android_environment -f ci_resources/Dockerfile.android .
