name: Test versions setting

on:
  push:
    branches:
      - 'feature/AND-10052_store_tasks_in_aws'
  workflow_dispatch:
    inputs:
      build_description:
        description: >
          Optional additional info about the build
        type: string
  workflow_call:
    secrets:
      FIREBASE_APP_ID_INTERNAL:
        required: true
      FIREBASE_CLI_TOKEN:
        required: true
      # Token must have read access to all the submodule repositories
      GH_MOBILE_PAT:
        required: true
jobs:
  generate-release-name:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch_name: ["releases/5.21", "hotfix/5.21.1", "develop", "test", "feature/AND-123", "feature/releases/5.21", "releases/XXX"]
    outputs:
      versionName: ${{ steps.get_version_name.outputs.versionName }}
    steps:
      - name: Test
        run: |
          pwd
          echo ${{ github.workspace }}

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine release version
        id: get_version_name
        run: |
          BRANCH=${{ matrix.branch_name }}
          echo "Testing with branch: $BRANCH"
          
          if [[ "$BRANCH" =~ ^(releases|hotfix)/([0-9]+)\.([0-9]+)(\.[0-9]+)?$ ]]; then
            MAJOR=${BASH_REMATCH[2]}
            MINOR=${BASH_REMATCH[3]}
            PATCH=${BASH_REMATCH[4]:-.0}
            VERSION="${MAJOR}.${MINOR}${PATCH}"
          else
            echo "Running script"
            ./ci_resources/find-latest-release-branch.sh origin/$BRANCH
            LATEST_BRANCH=$(< 'find-latest-release-branch.output')
          
            if [[ "$LATEST_BRANCH" =~ releases/([0-9]+)\.([0-9]+) ]]; then
              MAJOR=${BASH_REMATCH[1]}
              MINOR=${BASH_REMATCH[2]}
              NEW_MINOR=$((MINOR + 1))
              VERSION="${MAJOR}.${NEW_MINOR}.0"
            else
              echo "Failed to determine version"
              exit 1
            fi
          fi
          
          echo "versionName=$VERSION" >> $GITHUB_OUTPUT

      - name: Output release name
        run: |
          echo "Branch: ${{ matrix.branch_name }} → Release version: ${{ steps.get_version_name.outputs.versionName }}"