name: Test versions setting

on:
  push:
    branches:
      - 'feature/AND-10052_store_tasks_in_aws'
  workflow_dispatch:
    inputs:
      build_description:
        description: >
          Optional additional info about the build
        type: string
  workflow_call:
    secrets:
      FIREBASE_APP_ID_INTERNAL:
        required: true
      FIREBASE_CLI_TOKEN:
        required: true
      # Token must have read access to all the submodule repositories
      GH_MOBILE_PAT:
        required: true
jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Token
        run: |
          echo "Token length: $(echo -n "${{ secrets.TEST_CLONE_REPO_KEY }}" | wc -c)"

      - name: Push to mirror
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote -v
          
          
          git remote add mirror https://x-access-token:${{ secrets.TEST_CLONE_REPO_KEY }}@github.com/tangem-developments/tangem-app-android-clone-test.git
          echo "push"
          git push --mirror mirror